[package]
name = "event_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
screenshot_lib = { path = "../screenshot_lib" }
shortcut_lib = { path = "../shortcut_lib" }

image = "0.24.7"
native-dialog = "0.6.4"

[dependencies.druid]
version = "0.8.3"
features = ["im", "svg", "image"]
