[package]
name = "event_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
screenshots = "0.7.1"
bincode = "1.3.3"
shortcut_lib = { path = "../shortcut_lib" }
chrono = "0.4.26"
directories = "5.0.1"

[dependencies.druid]
version = "0.8.3"
features = ["im", "svg", "image"]
