[package]
name = "gui_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
event_lib = { path = "../event_lib" }
shortcut_lib = { path = "../shortcut_lib" }
screenshot_lib ={ path = "../screenshot_lib" }

strum = "0.25.0"

[dependencies.druid]
version = "0.8.3"
features = ["im", "svg", "image"]
