[package]
name = "gui_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#image = "0.24.7"

event_lib = { path = "../event_lib" }
shortcut_lib = { path = "../shortcut_lib" }
screenshot_lib ={ path = "../screenshot_lib" }

strum = "0.25.0"
native-dialog = "0.6.4"
directories = "5.0.1"

[dependencies.druid]
version = "0.8.3"
features = ["im", "svg", "image"]
