[package]
name = "screenshot_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
screenshots = "0.8.2"

[dependencies.druid]
version = "0.8.3"
features = ["im", "svg", "image"]
