[package]
name = "shortcut_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
directories = "5.0.1"
serde = { version = "1.0", features = ["derive"] }
strum = "0.25.0"
strum_macros = "0.25"
toml = "0.8.0"

[dependencies.druid]
version = "0.8.3"
features = ["im", "svg", "image"]
